In [13]:
import random
from faker import Faker
import pandas as pd
fake = Faker()

In [14]:
occupations = ['software_engineer', 'data_analyst', 'student', 'teacher', 'entrepreneur',
               'research_assistant', 'nurse', 'architect', 'quality_assurance_analyst',
               'doctor', 'lawyer', 'marketing_manager', 'financial_analyst', 'graphic_designer',
               'journalist', 'it_manager', 'product_manager', 'psychologist', 'social_worker',
               'business_analyst', 'mechanical_engineer', 'electrician', 'athlete', 'chef', 'events_planner']

In [15]:
occupations_education = {
    'software_engineer': ['BTech', 'MTech', 'BE'],
    'data_analyst': ['BTech', 'MTech', 'BE'],
    'student': ['BTech', 'MTech', 'BE'],
    'teacher': ['BEd', 'MEd'],
    'entrepreneur': ['Diploma', 'BBA', 'MBA'],
    'research_assistant': ['MS', 'MTech', 'PhD'],
    'nurse': ['BSN', 'Diploma'],
    'architect': ['BArch', 'MArch'],
    'quality_assurance_analyst': ['BTech', 'MTech', 'BE'],
    'doctor': ['MBBS', 'MD'],
    'lawyer': ['LLB', 'JD'],
    'marketing_manager': ['MBA', 'BBA'],
    'financial_analyst': ['MBA', 'BBA'],
    'graphic_designer': ['BFA', 'Diploma'],
    'journalist': ['BJMC', 'MA Journalism'],
    'it_manager': ['BTech', 'MTech', 'BE'],
    'product_manager': ['MBA', 'BBA'],
    'psychologist': ['BA Psychology', 'MA Psychology'],
    'social_worker': ['BA', 'BBA'],
    'business_analyst': ['MBA', 'BBA'],
    'mechanical_engineer': ['BTech', 'MTech', 'BE'],
    'electrician': ['ITI Electrician', 'Diploma'],
    'athlete': ['Sports Training'],
    'chef': ['Culinary School Diploma'],
    'events_planner': ['Event Management Certification']
}

In [16]:
specializations = {
    'software_engineer': ['Web Development', 'Mobile App Development', 'Data Science', 'Machine Learning',
                          'Artificial Intelligence', 'Software Testing', 'Database Management',
                          'Cloud Computing', 'Cybersecurity', 'UI/UX Design', 'DevOps', 'Embedded Systems'],
    'data_analyst': ['Data Mining', 'Statistical Analysis', 'Data Visualization', 'Machine Learning',
                     'Business Intelligence', 'Predictive Analytics', 'Big Data Analytics',
                     'Quantitative Analysis', 'Financial Analysis', 'Marketing Analytics',
                     'Text Mining', 'Social Network Analysis'],
    'student': ['Computer Science', 'Information Technology', 'Mechanical Engineering',
                'Electrical Engineering', 'Civil Engineering', 'Chemical Engineering',
                'Biomedical Engineering'],
    'teacher': ['Elementary Education', 'Secondary Education', 'Special Education',
                'Mathematics Education', 'Science Education', 'English Education',
                'Social Studies Education', 'Physical Education', 'Music Education',
                'Art Education', 'Foreign Language Education'],
    'entrepreneur': ['Business Administration', 'Management', 'Marketing', 'Finance',
                     'Entrepreneurship', 'Economics', 'Strategy', 'Innovation',
                     'Start-up Management', 'Sales and Negotiation'],
    'research_assistant': ['Biology', 'Chemistry', 'Physics'],
    'nurse': ['Nursing', 'Healthcare'],
    'architect': ['Architecture', 'Civil Engineering'],
    'quality_assurance_analyst': ['Software Testing', 'Test Automation', 'Quality Management Systems',
                                  'Performance Testing', 'Regression Testing', 'User Acceptance Testing',
                                  'Agile Testing', 'Security Testing', 'Mobile App Testing',
                                  'Web Application Testing', 'Test Documentation', 'Defect Tracking'],
    'doctor': ['General Medicine', 'Cardiology', 'Dermatology', 'Pediatrics', 'Orthopedics', 'Ophthalmology',
               'Gynecology', 'Neurology', 'Psychiatry', 'Radiology', 'Oncology', 'Anesthesiology',
               'ENT (Ear, Nose, and Throat)', 'Emergency Medicine', 'Internal Medicine',
               'Endocrinology', 'Gastroenterology', 'Nephrology', 'Pulmonology', 'Rheumatology'],
    'lawyer': ['Criminal Law', 'Corporate Law', 'Family Law', 'Intellectual Property Law',
               'Environmental Law', 'Immigration Law', 'Labor Law', 'Real Estate Law',
               'Healthcare Law', 'Tax Law', 'International Law', 'Civil Rights Law'],
    'marketing_manager': ['Marketing Strategy', 'Digital Marketing', 'Brand Management',
                          'Social Media Marketing', 'Content Marketing', 'Market Research',
                          'Advertising', 'Public Relations', 'Product Management'],
    'financial_analyst': ['Financial Planning', 'Investment Analysis', 'Risk Management',
                          'Financial Modeling', 'Portfolio Management', 'Valuation',
                          'Derivatives Analysis', 'Economic Research', 'Asset Allocation'],
    'graphic_designer': ['Print Design', 'Web Design', 'Logo Design', 'UI/UX Design',
                         'Branding', 'Illustration', 'Motion Graphics', 'Packaging Design',
                         'Typography', 'Visual Identity Design', 'Advertising Design'],
    'journalist': ['Investigative Journalism', 'Broadcast Journalism', 'Data Journalism',
                   'Political Journalism', 'Business Journalism', 'Science Journalism',
                   'Sports Journalism', 'Feature Writing', 'Photojournalism'],
    'it_manager': ['IT Infrastructure Management', 'Network Administration',
                   'Information Security', 'Database Management', 'Cloud Computing',
                   'IT Project Management', 'System Analysis and Design',
                   'Business Process Automation', 'IT Governance', 'Cybersecurity'],
    'product_manager': ['Product Strategy', 'Product Development', 'User Experience (UX) Design',
                        'Product Launch and Marketing', 'Agile Product Management',
                        'Data-driven Product Management', 'Market Research and Analysis',
                        'Product Roadmapping', 'Competitor Analysis', 'Customer Insights'],
'psychologist': ['Clinical Psychology', 'Counseling Psychology', 'Organizational Psychology',
                     'Educational Psychology', 'Forensic Psychology', 'Health Psychology',
                     'Child and Adolescent Psychology', 'Neuropsychology', 'Research Psychology'],
    'social_worker': ['Community Outreach', 'Family Services', 'Mental Health',
                      'Substance Abuse Counseling', 'Child Welfare', 'Gerontology',
                      'School Social Work', 'Medical Social Work', 'Policy Advocacy'],
    'business_analyst': ['Business Process Analysis', 'Requirements Gathering', 'Data Analysis',
                         'Project Management', 'Market Research', 'Financial Analysis',
                         'Systems Analysis', 'Business Intelligence', 'Risk Assessment'],
    'mechanical_engineer': ['Mechanical Design', 'Thermodynamics', 'Robotics'],
    'electrician': ['Electrical Wiring', 'Power Systems', 'Renewable Energy'],
    'athlete': ['Sports Training', 'Sports Psychology', 'Sports Nutrition'],
    'chef': ['Culinary Arts', 'Bakery and Pastry', 'International Cuisine'],
    'events_planner': ['Event Coordination', 'Event Marketing', 'Venue Management']
}

In [17]:
num_samples = 1000
data = []

for i in range(num_samples):
    uid = f"uid{i+1:06d}"
    occupation = random.choice(occupations)
    education = random.choice(occupations_education[occupation])
    specialization = random.choice(specializations[occupation])
    
    sex = random.choice(['M', 'F'])
    age_group = random.choice(['20-25', '25-30', '30-35', '35-40', '40-45'])
    company_name = fake.company()
    city = fake.city()
    zipcode = fake.zipcode()
    job = random.randint(0, 1)
    career_development = random.randint(0, 1)
    personal_growth = random.randint(0, 1)
    educational_content = random.randint(0, 1)
    healthcare = random.randint(0, 1)

    data.append([uid, sex, age_group, occupation, company_name, city, zipcode, education, specialization,
                 job, career_development, personal_growth, educational_content, healthcare])

In [18]:
columns = ['User ID', 'Sex', 'Age-group', 'Occupation', 'Company Name', 'City', 'Zipcode',
           'Education', 'Specialization', 'Job', 'Career Development', 'Personal Growth',
           'Educational Content', 'Healthcare']
df = pd.DataFrame(data, columns=columns)
df.head()

,User ID,Sex,Age-group,Occupation,Company Name,City,Zipcode,Education,Specialization,Job,Career Development,Personal Growth,Educational Content,Healthcare
0,uid000001,F,35-40,financial_analyst,"Carpenter, Johnson and Gould",West Alexandrafurt,91685,BBA,Risk Management,1,1,0,0,1
1,uid000002,F,30-35,product_manager,Howell-Wells,Nicolestad,13776,BBA,Agile Product Management,0,1,0,0,1
2,uid000003,M,20-25,architect,Mendoza LLC,New Tamarafurt,07120,BArch,Civil Engineering,0,1,1,1,0
3,uid000004,M,20-25,financial_analyst,"Chandler, Adams and Freeman",Huangfurt,24138,MBA,Economic Research,0,0,0,1,1
4,uid000005,M,25-30,architect,Lee Inc,Larafort,81916,BArch,Civil Engineering,1,1,0,1,1